version: '3'
services:
  meuse:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: ../.
    environment:
      - "MEUSE_CONFIGURATION=/app/config/meuse.yaml"
    ports:
      - "8855:8855"
    volumes:
      - "./meuse.yaml:/app/config/meuse.yaml"
      - "./crates/:/app/crates/"
      - "./registry/:/app/registry/"
      
    links:
      - "database"
    
  database:
    ports:
      - "5432:5432"
    #image: postgres:14.4
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_DB=meuse"
      - "POSTGRES_USER=meuse"
      - "POSTGRES_PASSWORD=meuse"
    # volumes:
    #   - "/home/ashok/docker/app/db/init.sql:/opt/app/init.sql"