version: '3'
services:
  meuse:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: ../.
    user: "200:200"
    environment:    
      - "MEUSE_CONFIGURATION=/dev/resources/config.yaml"
    ports:
      - "8855:8855"
    volumes:
      - "./meuse.yaml:/dev/resources/config.yaml"
      - "./crates/:/app/crates/"
      #- meuse-crates:/app/crates/
      - "./registry/:/app/registry/"
      
    links:
      - "database"
    
  database:
    ports:
      - "5432:5432"
    #image: postgres:14.4
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_DB=meuse"
      - "POSTGRES_USER=meuse"
      - "POSTGRES_PASSWORD=meuse"
    # volumes:
    #   - "/home/ashok/docker/app/db/init.sql:/opt/app/init.sql"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"    
volumes:
  meuse-crates: